# Generated by Django 5.0.14 on 2026-02-05 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elo_rating", models.IntegerField(default=1500)),
                ("comparisons_count", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в wishlist",
                "verbose_name_plural": "Товары в wishlist",
                "ordering": ["-elo_rating", "-added_at"],
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item1_rating_before", models.IntegerField()),
                ("item2_rating_before", models.IntegerField()),
                ("item1_rating_after", models.IntegerField()),
                ("item2_rating_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_item1",
                        to="wishlist.item",
                    ),
                ),
                (
                    "item2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_item2",
                        to="wishlist.item",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_comparisons",
                        to="wishlist.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сравнение",
                "verbose_name_plural": "Сравнения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_code",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Артикул",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "marketplace",
                    models.CharField(
                        choices=[
                            ("ozon", "Ozon"),
                            ("wildberries", "Wildberries"),
                            ("other", "Другое"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Первое обнаружение"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "last_price_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя проверка цены"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар в каталоге",
                "verbose_name_plural": "Товары в каталоге",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["marketplace", "article_code"],
                        name="wishlist_pr_marketp_ee0c09_idx",
                    ),
                    models.Index(
                        fields=["-last_updated"], name="wishlist_pr_last_up_edd56a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="wishlist.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "История цены",
                "verbose_name_plural": "История цен",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="wishlist.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product"
            ),
        ),
    ]
