# Generated by Django 5.0.14 on 2026-02-06 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="elo_rating",
            field=models.IntegerField(db_index=True, default=1500),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="comparison",
            index=models.Index(
                fields=["user", "-created_at"], name="wishlist_co_user_id_a40b96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "is_active"], name="wishlist_it_user_id_0da2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "is_active", "-elo_rating"],
                name="wishlist_it_user_id_ceee01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "added_at"], name="wishlist_it_user_id_841e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "comparisons_count"],
                name="wishlist_it_user_id_eb450f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product", "-checked_at"], name="wishlist_pr_product_5dee09_idx"
            ),
        ),
    ]
