# Generated by Django 5.0.14 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_alter_item_elo_rating_alter_item_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Категория"),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Количество отзывов"),
        ),
    ]
