# Generated by Django 5.0.14 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0003_product_category_reviews_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("wb_share_text", "WB Share Text"),
                            ("wb_selenium_favorites", "WB Selenium Favorites"),
                        ],
                        default="wb_share_text",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("enriching", "Enriching"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_links", models.IntegerField(default=0)),
                ("imported_count", models.IntegerField(default=0)),
                ("created_count", models.IntegerField(default=0)),
                ("reactivated_count", models.IntegerField(default=0)),
                ("duplicates_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("enrich_task_id", models.CharField(blank=True, max_length=100, null=True)),
                ("api_enriched_count", models.IntegerField(default=0)),
                ("selenium_enriched_count", models.IntegerField(default=0)),
                ("fast_import_ms", models.IntegerField(blank=True, null=True)),
                ("enrich_api_ms", models.IntegerField(blank=True, null=True)),
                ("enrich_selenium_ms", models.IntegerField(blank=True, null=True)),
                ("total_ms", models.IntegerField(blank=True, null=True)),
                ("message", models.TextField(blank=True, default="")),
                ("sample_errors", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["user", "-started_at"], name="wishlist_im_user_id_36fef0_idx"),
                    models.Index(fields=["status", "-started_at"], name="wishlist_im_status_36f539_idx"),
                ],
            },
        ),
    ]
