# Generated by Django 5.0.14 on 2026-02-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0004_importrun"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="importrun",
            new_name="wishlist_im_user_id_819db7_idx",
            old_name="wishlist_im_user_id_36fef0_idx",
        ),
        migrations.RenameIndex(
            model_name="importrun",
            new_name="wishlist_im_status_35f389_idx",
            old_name="wishlist_im_status_36f539_idx",
        ),
        migrations.AlterField(
            model_name="importrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("wb_share_text", "WB Share Text"),
                    ("wb_selenium_favorites", "WB Selenium Favorites"),
                    ("ozon_selenium_favorites", "Ozon Selenium Favorites"),
                ],
                default="wb_share_text",
                max_length=50,
            ),
        ),
    ]
